const fs = require('fs');
const path = require('path');
const quotaChecker = require('../utils/quota_checker');
const validator = require('../utils/validator');
const config = require('../utils/config');
const groqClient = require('../utils/groq_client');
const logger = require('../utils/logger');
const heartbeat = require('../utils/heartbeat');
const memory = require('../utils/memory');
const reviewer = require('./reviewer_agent');
const worker = require('./worker_template');

const ROOT = path.resolve(__dirname, '..');
const INPUT_DIR = path.join(ROOT, 'input');
const OUTPUT_DIR = path.join(ROOT, 'output');
const SELECTED_DIR = path.join(ROOT, 'selected');
const PROMPT_FILE = path.join(INPUT_DIR, 'PROMPT.txt');

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function loadPrompt() {
  if (!fs.existsSync(PROMPT_FILE)) {
    return null;
  }
  const raw = fs.readFileSync(PROMPT_FILE, 'utf8').trim();
  return raw.length > 0 ? raw : null;
}

function saveOutputFiles(generatedFiles) {
  generatedFiles.forEach((file) => {
    const destination = path.join(OUTPUT_DIR, file.fileName);
    fs.writeFileSync(destination, file.content, 'utf8');
    logger.info('file.saved', { file: destination });
  });
}

function saveResult(result) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const resultPath = path.join(OUTPUT_DIR, `result_${timestamp}.json`);
  fs.writeFileSync(resultPath, JSON.stringify(result, null, 2), 'utf8');
  logger.info('result.saved', { path: resultPath });
  return resultPath;
}

const SYSTEM_PROMPT = `You are ron_GIT, an expert AI developer. 
Your task is to generate high-quality code based on the user's prompt.
You MUST format your response exactly like this:

SUMMARY: [One sentence summary]

FILE: [filename1] (e.g., 1.html)
\`\`\`
[code content]
\`\`\`

FILE: [filename2]
\`\`\`
[code content]
\`\`\`

Ensure all code is functional, well-commented, and premium in quality. 
Avoid external dependencies unless requested. If you need multiple files (HTML, CSS, JS), list them all using the FILE: marker.`;

async function main() {
  ensureDir(INPUT_DIR);
  ensureDir(OUTPUT_DIR);
  ensureDir(SELECTED_DIR);

  const heartbeatId = heartbeat.startHeartbeat(config.getAgentLoopDelay());
  logger.info('architect.start', {
    enableGroq: config.isGroqEnabled(),
    agentLoopDelay: config.getAgentLoopDelay(),
    maxContextFiles: config.getMaxContextFiles(),
  });

  const quota = quotaChecker.getQuota();
  if (!quotaChecker.canConsume(quota)) {
    logger.error('quota.exceeded', { quota });
    heartbeat.stopHeartbeat();
    process.exit(1);
  }

  let prompt = loadPrompt();
  if (prompt === null || prompt.toLowerCase() === 'stop') {
    prompt = 'Create a minimal HTML game with one file.';
    logger.info('prompt.fallback', { prompt });
  }

  if (!validator.isValidPrompt(prompt)) {
    logger.error('prompt.invalid', { prompt });
    heartbeat.stopHeartbeat();
    process.exit(1);
  }

  // --- MEMORY INTEGRATION (Intelligence Phase 2) ---
  const pastSuccesses = memory.loadMemory(5);
  const pastLessons = memory.getRecentLessons(3);
  
  let historyPrompt = '';
  if (pastSuccesses.length > 0) {
    historyPrompt += '\n\n### PAST SUCCESSFUL INTERACTIONS:\n' + 
      pastSuccesses.map(m => `- Task: ${m.prompt.slice(0, 50)}...\n  Summary: ${m.resultSummary}`).join('\n');
  }
  if (pastLessons.length > 0) {
    historyPrompt += '\n\n### LESSONS LEARNED (CRITICAL FIXES):\n' + 
      pastLessons.map(l => `- Failed Task: ${l.prompt.slice(0, 50)}...\n  Errors to Avoid: ${l.errors.join(', ')}`).join('\n');
  }

  // Token Management: "Fall back bit by bit"
  // Simple heuristic: If historyPrompt is > 2000 chars, trim it
  if (historyPrompt.length > 2000) {
    logger.warn('memory.trimming', { length: historyPrompt.length });
    historyPrompt = historyPrompt.slice(0, 2000) + '... [TRUNCATED]';
  }

  const fullPrompt = `${SYSTEM_PROMPT}${historyPrompt}\n\nUser Request: ${prompt}`;
  logger.info('architect.prompt', { prompt, hasHistory: !!historyPrompt });

  const groqResponse = await groqClient.callGroq(fullPrompt);
  let taskResult;

  if (groqResponse.success && groqResponse.content) {
    const content = groqResponse.content;
    const summaryMatch = content.match(/SUMMARY:\s*(.*)/i);
    const summary = summaryMatch ? summaryMatch[1].trim() : 'Generated by ron_GIT';
    
    const generatedFiles = [];
    const fileBlocks = content.split(/FILE:\s*/i).slice(1);
    
    fileBlocks.forEach(block => {
      const lines = block.split('\n');
      const fileName = lines[0].trim();
      const codeBlockMatch = block.match(/```(?:\w+)?\n([\s\S]*?)\n```/);
      if (codeBlockMatch) {
        generatedFiles.push({
          fileName,
          content: codeBlockMatch[1]
        });
      }
    });

    if (generatedFiles.length > 0) {
      taskResult = {
        prompt,
        summary,
        generatedFiles
      };
      logger.info('groq.success', { summary, fileCount: generatedFiles.length });
    } else {
      logger.warn('groq.parseFail.noFiles', { content });
      taskResult = worker.runTask({ prompt });
    }
  } else {
    logger.warn('groq.fallback', { reason: groqResponse.message || groqResponse.status });
    taskResult = worker.runTask({ prompt });
  }

  logger.info('architect.validation.start', { taskResult });

  const validation = reviewer.validateResult(taskResult);
  if (!validation.ok) {
    logger.error('review.failed', { errors: validation.errors });
    heartbeat.stopHeartbeat();
    process.exit(1);
  }

  const output = {
    metadata: {
      prompt,
      timestamp: new Date().toISOString(),
      version: 'ron_GIT_v1.0',
      groqEnabled: config.isGroqEnabled(),
      source: groqResponse.success ? 'groq' : 'fallback',
    },
    result: taskResult,
  };

  saveOutputFiles(taskResult.generatedFiles || []);
  const savedPath = saveResult(output);
  quotaChecker.consumeQuota();
  memory.recordInteraction({
    prompt,
    resultSummary: taskResult.summary,
    source: groqResponse.success ? 'groq' : 'fallback',
    payload: {
      fileCount: (taskResult.generatedFiles || []).length,
      responseStatus: groqResponse.status || null,
    },
  });
  logger.info('architect.complete', { savedPath });
  heartbeat.stopHeartbeat();
  logger.updateStatus('Workflow complete', { savedPath });

  console.log('Workflow complete. Result saved to', savedPath);
}

if (require.main === module) {
  main().catch((error) => {
    logger.error('architect.unhandledError', { error: error.message });
    console.error('Architect agent failed:', error);
    process.exit(1);
  });
}

module.exports = { main };
